version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6378:6379"

  django:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS=True
    depends_on:
      - redis
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8000