# Generated by Django 5.1.1 on 2024-09-22 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0002_alter_gold_available_balance"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GoldTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("buy", "Buy"),
                            ("sell", "Sell"),
                            ("deposit", "Deposit"),
                        ],
                        max_length=7,
                    ),
                ),
                ("grams", models.FloatField()),
                (
                    "amount_in_currency",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("transaction_date", models.DateTimeField(auto_now_add=True)),
                (
                    "commission_rate",
                    models.DecimalField(decimal_places=2, default=0.02, max_digits=5),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
